stages:
  - deploy

staging:
  stage: deploy
  script:
    - cd /var/www/nginx/artis-dapps-voting
    - git pull
    - . ~/.nvm/nvm.sh
    - npm ci
    - rm -r build
    - CI=false npm run build
#    - ./update-artis-network-specs.sh